### PR TITLE
Add mixed return sniff

### LINKED ISSUE #110: Sniff to prevent `mixed` type hints and return types?

### PR DESCRIPTION
**Pull request by fentie**
Fixes #110

### CODE REVIEW

**Comment by bmitch** [comment]
Thanks very much @fentie 

The build is failing, any chance you could take a look at it and see if you can get it to pass?

Let me know if you need a hand getting it passing and I could take a look.

**Comment by fentie** [comment]
Alright, now I think I could use a hand. I'm either stuck with the 7.1+ syntax failing on 7.0, or the 7.1+ builds demanding the 7.1 syntax. It looks like we either need an additional segmentation of sniffs in `.travis.yml` or drop 7.0 support, neither of which I feel comfortable deciding for your project

**Comment by bmitch** [comment]
@fentie No problem. I should probably add a section in the readme that provides more information on the tests.

I'll take a look at this as soon as I can. Thanks for the PR!

**Comment by bmitch** [comment]
Thanks @fentie I've merged this and will fix it up.

**Pull request merged**
